[build]
  # The directory containing the build output
  publish = "build"
  # The build command to run (this will build the React app)
  command = "npm run build"

[[redirects]]
  # Redirect all routes to index.html (for single-page apps)
  from = "/*"
  to = "/index.html"
  status = 200
